import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.dashboard': 'Tableau de Bord',
    'nav.treasury': 'Trésorerie',
    'nav.invoicing': 'Facturation & Devis',
    'nav.reconciliation': 'Rapprochement Bancaire',
    'nav.budgets': 'Gestion Budgétaire',
    'nav.journal': 'Journal & Saisie',
    'nav.recurring': 'Écritures Récurrentes',
    'nav.ledger': 'Grand Livre',
    'nav.trial_balance': 'Balance Générale',
    'nav.financials': 'États Financiers',
    'nav.third_parties': 'CRM (Clients & Fournisseurs)',
    'nav.assets': 'Immobilisations',
    'nav.vat': 'Fiscalité',
    'nav.payroll': 'Paie',
    'nav.company': 'Création Entreprise',
    'nav.compliance': 'Conformité & Audit',
    'nav.financial_auditor': 'Audit Financier IA',
    'nav.accounts': 'Plan Comptable',
    'nav.team': 'Gestion d\'Équipe',
    'nav.assistant': 'Conseiller Ory',
    'nav.tax_assistant': 'Audit Fiscal Expert',
    'nav.settings': 'Paramètres',
    'group.pilotage': 'Pilotage',
    'group.accounting': 'Comptabilité',
    'group.management': 'États & Gestion',
    'group.revision': 'Révision',
    'group.payroll': 'Paie & RH',
    'group.tools': 'Outils',
    'role.admin': 'Administrateur',
    'role.user': 'Utilisateur',
    'auth.logout': 'Déconnexion',
    'settings.description': 'Configuration générale de votre comptabilité.',
    'settings.language_title': 'Langue',
    'settings.language_description': 'Choisissez votre langue préférée pour l\'interface.',
    'search.placeholder': 'Rechercher un compte, une écriture, un tiers...',
    'search.results': 'Résultats de recherche',
    'search.no_results': 'Aucun résultat trouvé pour',
    'theme.light': 'Mode Clair',
    'theme.dark': 'Mode Sombre',
    'common.help': 'Aide',
    'notifications.title': 'Notifications',
    'notifications.mark_read': 'Tout marquer comme lu',
    'notifications.view_all': 'Voir toutes les notifications',
    'onboarding.welcome_title': 'Bienvenue sur OryCompta',
    'onboarding.welcome_subtitle': 'L\'excellence comptable au service de votre ambition.',
    'onboarding.welcome_description': 'Nous allons vous accompagner dans la configuration de votre environnement de travail conforme aux normes SYSCOHADA.',
    'onboarding.start_button': 'Commencer la configuration',
    'onboarding.step_identity': 'Identité',
    'onboarding.step_tax': 'Fiscalité',
    'onboarding.step_capital': 'Capital',
    'onboarding.step_treasury': 'Trésorerie',
    'onboarding.step_team': 'Équipe',
    'onboarding.step_modules': 'Modules',
    'onboarding.step_launch': 'Lancement',
    'onboarding.company_name': 'Dénomination Sociale',
    'onboarding.legal_form': 'Forme Juridique',
    'onboarding.manager_name': 'Gérant / Directeur Général',
    'onboarding.country': 'Pays du Siège',
    'onboarding.city': 'Ville',
    'onboarding.email': 'Email de contact',
    'onboarding.phone': 'Téléphone',
    'onboarding.next': 'Continuer',
    'onboarding.back': 'Retour',
    'onboarding.finish': 'Terminer la configuration',
    'onboarding.success_title': 'Félicitations !',
    'onboarding.success_message': 'Votre entreprise a été configurée avec succès.',
    'onboarding.error_name_required': 'Le nom de l\'entreprise est obligatoire',
    'onboarding.error_manager_required': 'Le nom du gérant est obligatoire',
    'onboarding.error_email_required': 'L\'email de contact est obligatoire',
    'onboarding.error_city_required': 'La ville est obligatoire',
    'onboarding.error_email_invalid': 'L\'email de contact est invalide',
    'onboarding.error_capital_mismatch': 'Le total des apports doit être égal au capital social',
    'onboarding.error_partners_required': 'Au moins un associé est requis',
    'onboarding.error_partner_name_required': 'Le nom de l\'associé est obligatoire',
    'onboarding.error_treasury_required': 'Au moins un compte de trésorerie est requis',
    'onboarding.error_treasury_name_required': 'Le nom du compte de trésorerie est obligatoire',
    'onboarding.error_user_email_invalid': 'L\'email de l\'utilisateur est invalide',
    'onboarding.error_user_name_required': 'Le nom de l\'utilisateur est obligatoire',
    'onboarding.error_accounting_mandatory': 'Le module de comptabilité est obligatoire',
    'onboarding.step_identity_desc': 'Informations légales et siège social',
    'onboarding.step_tax_desc': 'Régime fiscal et paramètres TVA',
    'onboarding.step_capital_desc': 'Structure du capital et associés',
    'onboarding.step_treasury_desc': 'Comptes bancaires et caisses',
    'onboarding.step_team_desc': 'Utilisateurs et accès',
    'onboarding.step_modules_desc': 'Activation des fonctionnalités',
    'onboarding.step_launch_desc': 'Vérification finale avant lancement',
    'onboarding.tip_identity': 'Assurez-vous que la dénomination sociale correspond exactement à celle figurant sur vos statuts. Le RCCM et l\'ID Fiscal sont essentiels pour vos futures factures conformes.',
    'onboarding.tip_tax': 'Le Système Normal est obligatoire pour les entreprises dépassant un certain CA. Le SMT est adapté aux petites structures.',
    'onboarding.tip_capital': 'Définissez ici le capital social de départ. Pour une SARL dans l\'espace OHADA, le capital minimum est généralement de 1 000 000 FCFA.',
    'onboarding.tip_treasury': 'Configurez vos comptes de trésorerie initiaux. Le solde initial correspond généralement au capital libéré déposé.',
    'onboarding.tip_team': 'Définissez les premiers utilisateurs. Par défaut, vous êtes l\'Administrateur Principal avec tous les droits.',
    'onboarding.tip_modules': 'Activez uniquement les modules dont vous avez besoin pour le moment. Vous pourrez toujours en activer d\'autres plus tard.',
    'onboarding.tip_launch': 'En cliquant sur "Lancer l\'application", le système va automatiquement générer les écritures de constitution.',
    'onboarding.initializing': 'Initialisation de votre environnement...',
    'onboarding.loading_step_1': 'Vérification des données...',
    'onboarding.loading_step_2': 'Création du dossier d\'entreprise...',
    'onboarding.loading_step_3': 'Configuration de l\'exercice fiscal...',
    'onboarding.loading_step_4': 'Initialisation du plan comptable...',
    'onboarding.loading_step_5': 'Génération des écritures de constitution...',
    'onboarding.loading_step_6': 'Configuration de la trésorerie...',
    'onboarding.loading_step_7': 'Finalisation de l\'onboarding...',
    'onboarding.error_generic': 'Une erreur est survenue. Veuillez réessayer.',
    'onboarding.sidebar_title': 'Aide à la création',
    'onboarding.sidebar_tip_1': 'Assurez-vous que la dénomination sociale correspond exactement à celle figurant sur vos statuts.',
    'onboarding.sidebar_tip_2': 'Le capital social minimum dépend de votre forme juridique (ex: 1M FCFA pour une SARL).',
    'onboarding.sidebar_tip_3': 'Vous pourrez ajouter d\'autres collaborateurs et définir leurs droits plus tard.',
    'onboarding.feature_compliance': 'Conformité',
    'onboarding.feature_compliance_desc': 'Respect strict des normes OHADA et fiscales locales.',
    'onboarding.feature_precision': 'Précision',
    'onboarding.feature_precision_desc': 'Calculs automatisés et tableaux de bord en temps réel.',
    'onboarding.feature_modular': 'Modulaire',
    'onboarding.feature_modular_desc': 'Activez uniquement les outils dont vous avez besoin.',
    'onboarding.summary_identity': 'Identité',
    'onboarding.summary_capital': 'Capital Social',
    'onboarding.summary_tax': 'Fiscalité',
    'onboarding.summary_accounting': 'Comptabilité',
    'onboarding.summary_treasury': 'Comptes de Trésorerie',
    'onboarding.summary_modules': 'Modules Activés',
    'onboarding.summary_ready': 'Prêt à démarrer ?',
    'onboarding.module_accounting': 'Comptabilité',
    'onboarding.module_invoicing': 'Facturation',
    'onboarding.module_crm': 'Clients',
    'onboarding.module_vendors': 'Fournisseurs',
    'onboarding.module_payroll': 'Paie',
    'onboarding.module_vat': 'TVA',
    'onboarding.module_assets': 'Immo',
    'onboarding.module_bankrec': 'Rapprochement',
    'onboarding.module_accounting_desc': 'Journal, Grand Livre, Bilan',
    'onboarding.module_invoicing_desc': 'Devis, Factures, Clients',
    'onboarding.module_crm_desc': 'Fiches clients, Suivi',
    'onboarding.module_vendors_desc': 'Achats, Dettes, Paiements',
    'onboarding.module_payroll_desc': 'Bulletins de paie, Social',
    'onboarding.module_vat_desc': 'Calcul auto, Formulaires',
    'onboarding.module_assets_desc': 'Amortissements, Registre',
    'onboarding.module_bankrec_desc': 'Pointage, Écarts',
    'onboarding.summary_partners': 'Associés',
    'onboarding.summary_costs': 'frais',
    'onboarding.summary_vat_exempt': 'Exonéré de TVA',
    'onboarding.summary_fiscal_start': 'Début',
    'onboarding.summary_auto_config': 'Configuration Automatique Recommandée',
    'common.confirm_delete': 'Voulez-vous vraiment supprimer cet élément ?',
    'common.confirm_delete_title': 'Confirmer la suppression',
    'common.delete': 'Supprimer',
    'common.cancel': 'Annuler',
    'common.confirm_irreversible': 'Cette action est irréversible.',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.duplicate': 'Dupliquer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.all': 'Tout',
    'common.none': 'Aucun',
    'common.date': 'Date',
    'common.description': 'Description',
    'common.amount': 'Montant',
    'common.reference': 'Référence',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.add': 'Ajouter',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.finish': 'Terminer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'journal.title': 'Journal des Opérations',
    'journal.new_entry': 'Nouvelle Écriture',
    'journal.expert_mode': 'Mode Expert',
    'journal.guided_mode': 'Mode Guidé',
    'journal.balance': 'Équilibrer',
    'journal.balanced': 'Équilibré',
    'journal.unbalanced': 'Non équilibré',
    'journal.debit': 'Débit',
    'journal.credit': 'Crédit',
    'journal.account': 'Compte',
    'journal.vat': 'TVA',
    'journal.payment_mode': 'Mode de Paiement',
    'journal.third_party': 'Tiers',
    'journal.notes': 'Notes',
    'journal.attachments': 'Pièces Jointes',
    'journal.ai_suggestions': 'Suggestions IA',
    'journal.scan_invoice': 'Scanner Facture',
    'journal.export_pdf': 'Exporter en PDF',
    'journal.export_excel': 'Exporter en Excel',
    'journal.filter_date_range': 'Période',
    'journal.filter_status': 'Statut',
    'journal.search_placeholder': 'Rechercher une transaction...',
    'currency.title': 'Gestion des Devises',
    'currency.description': 'Configurez vos taux de change par défaut.',
    'currency.add_rate': 'Ajouter un taux',
    'currency.from': 'De',
    'currency.to': 'Vers',
    'currency.rate': 'Taux',
    'currency.updated_at': 'Dernière mise à jour',
    'currency.base_currency': 'Devise de base',
    'currency.convert': 'Convertir',
    'currency.analyzer_title': 'Analyseur de Devises',
    'currency.analyzer_description': 'Analysez l\'impact des variations de change.',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.treasury': 'Treasury',
    'nav.invoicing': 'Invoicing & Quotes',
    'nav.reconciliation': 'Bank Reconciliation',
    'nav.budgets': 'Budget Management',
    'nav.journal': 'Journal & Entry',
    'nav.recurring': 'Recurring Entries',
    'nav.ledger': 'General Ledger',
    'nav.trial_balance': 'Trial Balance',
    'nav.financials': 'Financial Statements',
    'nav.third_parties': 'CRM (Clients & Suppliers)',
    'nav.assets': 'Fixed Assets',
    'nav.vat': 'Taxation',
    'nav.payroll': 'Payroll Management',
    'nav.company': 'Company Creation',
    'nav.compliance': 'Compliance & Audit',
    'nav.financial_auditor': 'AI Financial Audit',
    'nav.accounts': 'Chart of Accounts',
    'nav.team': 'Team Management',
    'nav.assistant': 'Ory Assistant',
    'nav.tax_assistant': 'Expert Tax Audit',
    'nav.settings': 'Settings',
    'group.pilotage': 'Steering',
    'group.accounting': 'Accounting',
    'group.management': 'Reports & Management',
    'group.revision': 'Review',
    'group.tools': 'Tools',
    'role.admin': 'Administrator',
    'role.user': 'User',
    'auth.logout': 'Logout',
    'settings.description': 'General configuration of your accounting.',
    'settings.language_title': 'Language',
    'settings.language_description': 'Choose your preferred language for the interface.',
    'search.placeholder': 'Search for an account, entry, third party...',
    'search.results': 'Search Results',
    'search.no_results': 'No results found for',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'common.help': 'Help',
    'notifications.title': 'Notifications',
    'notifications.mark_read': 'Mark all as read',
    'notifications.view_all': 'View all notifications',
    'onboarding.welcome_title': 'Welcome to OryCompta',
    'onboarding.welcome_subtitle': 'Accounting excellence at the service of your ambition.',
    'onboarding.welcome_description': 'We will guide you through the configuration of your work environment compliant with SYSCOHADA standards.',
    'onboarding.start_button': 'Start Configuration',
    'onboarding.step_identity': 'Identity',
    'onboarding.step_tax': 'Taxation',
    'onboarding.step_capital': 'Capital',
    'onboarding.step_treasury': 'Treasury',
    'onboarding.step_team': 'Team',
    'onboarding.step_modules': 'Modules',
    'onboarding.step_launch': 'Launch',
    'onboarding.company_name': 'Company Name',
    'onboarding.legal_form': 'Legal Form',
    'onboarding.manager_name': 'Manager / CEO',
    'onboarding.country': 'Country of Headquarters',
    'onboarding.city': 'City',
    'onboarding.email': 'Contact Email',
    'onboarding.phone': 'Phone',
    'onboarding.next': 'Continue',
    'onboarding.back': 'Back',
    'onboarding.finish': 'Finish Configuration',
    'onboarding.success_title': 'Congratulations!',
    'onboarding.success_message': 'Your company has been successfully configured.',
    'onboarding.error_name_required': 'Company name is required',
    'onboarding.error_manager_required': 'Manager name is required',
    'onboarding.error_email_required': 'Contact email is required',
    'onboarding.error_city_required': 'City is required',
    'onboarding.error_email_invalid': 'Contact email is invalid',
    'onboarding.error_capital_mismatch': 'Total contributions must match capital amount',
    'onboarding.error_partners_required': 'At least one partner is required',
    'onboarding.error_partner_name_required': 'Partner name is required',
    'onboarding.error_treasury_required': 'At least one treasury account is required',
    'onboarding.error_treasury_name_required': 'Treasury account name is required',
    'onboarding.error_user_email_invalid': 'User email is invalid',
    'onboarding.error_user_name_required': 'User name is required',
    'onboarding.error_accounting_mandatory': 'Accounting module is mandatory',
    'onboarding.step_identity_desc': 'Legal information and headquarters',
    'onboarding.step_tax_desc': 'Tax regime and VAT settings',
    'onboarding.step_capital_desc': 'Capital structure and partners',
    'onboarding.step_treasury_desc': 'Bank accounts and cash boxes',
    'onboarding.step_team_desc': 'Users and access',
    'onboarding.step_modules_desc': 'Feature activation',
    'onboarding.step_launch_desc': 'Final verification before launch',
    'onboarding.tip_identity': 'Ensure that the company name exactly matches the one on your statutes. RCCM and Tax ID are essential for your future compliant invoices.',
    'onboarding.tip_tax': 'The Normal System is mandatory for companies exceeding a certain turnover. SMT is suitable for small structures.',
    'onboarding.tip_capital': 'Define the starting share capital here. For a SARL in the OHADA area, the minimum capital is generally 1,000,000 FCFA.',
    'onboarding.tip_treasury': 'Set up your initial cash accounts. The initial balance generally corresponds to the paid-up capital deposited.',
    'onboarding.tip_team': 'Define the first users. By default, you are the Main Administrator with all rights.',
    'onboarding.tip_modules': 'Only activate the modules you need for now. You can always activate others later.',
    'onboarding.tip_launch': 'By clicking on "Launch Application", the system will automatically generate the constitution entries.',
    'onboarding.initializing': 'Initializing your environment...',
    'onboarding.loading_step_1': 'Verifying data...',
    'onboarding.loading_step_2': 'Creating company dossier...',
    'onboarding.loading_step_3': 'Configuring fiscal year...',
    'onboarding.loading_step_4': 'Initializing chart of accounts...',
    'onboarding.loading_step_5': 'Generating constitution entries...',
    'onboarding.loading_step_6': 'Configuring treasury...',
    'onboarding.loading_step_7': 'Finalizing onboarding...',
    'onboarding.error_generic': 'An error occurred. Please try again.',
    'onboarding.sidebar_title': 'Creation Help',
    'onboarding.sidebar_tip_1': 'Ensure the company name matches exactly what is on your statutes.',
    'onboarding.sidebar_tip_2': 'Minimum share capital depends on your legal form (e.g., 1M FCFA for a SARL).',
    'onboarding.sidebar_tip_3': 'You can add more collaborators and define their rights later.',
    'onboarding.feature_compliance': 'Compliance',
    'onboarding.feature_compliance_desc': 'Strict compliance with OHADA and local tax standards.',
    'onboarding.feature_precision': 'Precision',
    'onboarding.feature_precision_desc': 'Automated calculations and real-time dashboards.',
    'onboarding.feature_modular': 'Modular',
    'onboarding.feature_modular_desc': 'Only activate the tools you need.',
    'onboarding.summary_identity': 'Identity',
    'onboarding.summary_capital': 'Share Capital',
    'onboarding.summary_tax': 'Taxation',
    'onboarding.summary_accounting': 'Accounting',
    'onboarding.summary_treasury': 'Cash Accounts',
    'onboarding.summary_modules': 'Activated Modules',
    'onboarding.summary_ready': 'Ready to start?',
    'onboarding.module_accounting': 'Accounting',
    'onboarding.module_invoicing': 'Invoicing',
    'onboarding.module_crm': 'Clients',
    'onboarding.module_vendors': 'Suppliers',
    'onboarding.module_payroll': 'Payroll',
    'onboarding.module_vat': 'VAT',
    'onboarding.module_assets': 'Assets',
    'onboarding.module_bankrec': 'Reconciliation',
    'onboarding.module_accounting_desc': 'Journal, Ledger, Balance Sheet',
    'onboarding.module_invoicing_desc': 'Quotes, Invoices, Customers',
    'onboarding.module_crm_desc': 'Customer files, Tracking',
    'onboarding.module_vendors_desc': 'Purchases, Debts, Payments',
    'onboarding.module_payroll_desc': 'Pay slips, Social',
    'onboarding.module_vat_desc': 'Auto calculation, Forms',
    'onboarding.module_assets_desc': 'Depreciation, Register',
    'onboarding.module_bankrec_desc': 'Tick-off, Discrepancies',
    'onboarding.summary_partners': 'Partners',
    'onboarding.summary_costs': 'costs',
    'onboarding.summary_vat_exempt': 'VAT Exempt',
    'onboarding.summary_fiscal_start': 'Start',
    'onboarding.summary_auto_config': 'Recommended Automatic Configuration',
    'common.confirm_delete': 'Are you sure you want to delete this item?',
    'common.confirm_delete_title': 'Confirm Deletion',
    'common.delete': 'Delete',
    'common.cancel': 'Cancel',
    'common.confirm_irreversible': 'This action is irreversible.',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.duplicate': 'Duplicate',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.all': 'All',
    'common.none': 'None',
    'common.date': 'Date',
    'common.description': 'Description',
    'common.amount': 'Amount',
    'common.reference': 'Reference',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.finish': 'Finish',
    'common.yes': 'Yes',
    'common.no': 'No',
    'journal.title': 'Operations Journal',
    'journal.new_entry': 'New Entry',
    'journal.expert_mode': 'Expert Mode',
    'journal.guided_mode': 'Guided Mode',
    'journal.balance': 'Balance',
    'journal.balanced': 'Balanced',
    'journal.unbalanced': 'Unbalanced',
    'journal.debit': 'Debit',
    'journal.credit': 'Credit',
    'journal.account': 'Account',
    'journal.vat': 'VAT',
    'journal.payment_mode': 'Payment Mode',
    'journal.third_party': 'Third Party',
    'journal.notes': 'Notes',
    'journal.attachments': 'Attachments',
    'journal.ai_suggestions': 'AI Suggestions',
    'journal.scan_invoice': 'Scan Invoice',
    'journal.export_pdf': 'Export to PDF',
    'journal.export_excel': 'Export to Excel',
    'journal.filter_date_range': 'Period',
    'journal.filter_status': 'Status',
    'journal.search_placeholder': 'Search transaction...',
    'currency.title': 'Currency Management',
    'currency.description': 'Configure your default exchange rates.',
    'currency.add_rate': 'Add Rate',
    'currency.from': 'From',
    'currency.to': 'To',
    'currency.rate': 'Rate',
    'currency.updated_at': 'Last Update',
    'currency.base_currency': 'Base Currency',
    'currency.convert': 'Convert',
    'currency.analyzer_title': 'Currency Analyzer',
    'currency.analyzer_description': 'Analyze the impact of exchange rate variations.',
  },
  es: {
    'nav.dashboard': 'Tablero',
    'nav.treasury': 'Tesorería',
    'nav.invoicing': 'Facturación y Presupuestos',
    'nav.reconciliation': 'Conciliación Bancaria',
    'nav.budgets': 'Gestión Presupuestaria',
    'nav.journal': 'Diario y Asientos',
    'nav.recurring': 'Asientos Recurrentes',
    'nav.ledger': 'Libro Mayor',
    'nav.trial_balance': 'Balance de Sumas y Saldos',
    'nav.financials': 'Estados Financieros',
    'nav.third_parties': 'CRM (Clientes y Proveedores)',
    'nav.assets': 'Activos Fijos',
    'nav.vat': 'Fiscalidad',
    'nav.payroll': 'Gestión de Nóminas',
    'nav.company': 'Creación de Empresa',
    'nav.compliance': 'Cumplimiento y Auditoría',
    'nav.financial_auditor': 'Auditoría Financiera IA',
    'nav.accounts': 'Plan Contable',
    'nav.team': 'Gestión de Equipo',
    'nav.assistant': 'Asistente Ory',
    'nav.tax_assistant': 'Auditoría Fiscal Experta',
    'nav.settings': 'Ajustes',
    'group.pilotage': 'Pilotaje',
    'group.accounting': 'Contabilidad',
    'group.management': 'Estados y Gestión',
    'group.revision': 'Revisión',
    'group.tools': 'Herramientas',
    'role.admin': 'Administrador',
    'role.user': 'Usuario',
    'auth.logout': 'Cerrar Sesión',
    'settings.description': 'Configuración general de su contabilidad.',
    'settings.language_title': 'Idioma',
    'settings.language_description': 'Elija su idioma preferido para la interfaz.',
    'search.placeholder': 'Buscar una cuenta, asiento, tercero...',
    'search.results': 'Resultados de búsqueda',
    'search.no_results': 'No se encontraron resultados para',
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Oscuro',
    'common.help': 'Ayuda',
    'notifications.title': 'Notificaciones',
    'notifications.mark_read': 'Marcar todo como leído',
    'notifications.view_all': 'Ver todas las notificaciones',
    'onboarding.welcome_title': 'Bienvenido a OryCompta',
    'onboarding.welcome_subtitle': 'Excelencia contable al servicio de su ambición.',
    'onboarding.welcome_description': 'Le acompañaremos en la configuración de su entorno de travail conforme a las normas SYSCOHADA.',
    'onboarding.start_button': 'Iniciar Configuración',
    'onboarding.step_identity': 'Identidad',
    'onboarding.step_tax': 'Fiscalidad',
    'onboarding.step_capital': 'Capital',
    'onboarding.step_treasury': 'Tesorería',
    'onboarding.step_team': 'Equipo',
    'onboarding.step_modules': 'Módulos',
    'onboarding.step_launch': 'Lanzamiento',
    'onboarding.company_name': 'Nombre de la Empresa',
    'onboarding.legal_form': 'Forma Jurídica',
    'onboarding.manager_name': 'Gerente / Director General',
    'onboarding.country': 'País de la Sede',
    'onboarding.city': 'Ciudad',
    'onboarding.email': 'Correo de contacto',
    'onboarding.phone': 'Teléfono',
    'onboarding.next': 'Continuar',
    'onboarding.back': 'Atrás',
    'onboarding.finish': 'Finalizar Configuración',
    'onboarding.success_title': '¡Felicitaciones!',
    'onboarding.success_message': 'Su empresa ha sido configurada con éxito.',
    'onboarding.error_name_required': 'El nombre de la empresa es obligatorio',
    'onboarding.error_manager_required': 'El nombre del gerente es obligatorio',
    'onboarding.error_email_required': 'El correo electrónico de contacto es obligatorio',
    'onboarding.error_city_required': 'La ciudad es obligatoria',
    'onboarding.error_email_invalid': 'El correo electrónico de contacto no es válido',
    'onboarding.error_capital_mismatch': 'El total de las aportaciones debe coincidir con el capital social',
    'onboarding.error_partners_required': 'Se requiere al menos un socio',
    'onboarding.error_partner_name_required': 'El nombre del socio es obligatorio',
    'onboarding.error_treasury_required': 'Se requiere al moins una cuenta de tesorería',
    'onboarding.error_treasury_name_required': 'El nombre de la cuenta de tesorería es obligatorio',
    'onboarding.error_user_email_invalid': 'El correo electrónico del usuario no es válido',
    'onboarding.error_user_name_required': 'El nombre del usuario es obligatorio',
    'onboarding.error_accounting_mandatory': 'El módulo de contabilidad es obligatorio',
    'onboarding.step_identity_desc': 'Información legal y sede social',
    'onboarding.step_tax_desc': 'Régimen fiscal y ajustes de IVA',
    'onboarding.step_capital_desc': 'Estructura de capital y socios',
    'onboarding.step_treasury_desc': 'Cuentas bancarias y cajas',
    'onboarding.step_team_desc': 'Usuarios y acceso',
    'onboarding.step_modules_desc': 'Activación de funciones',
    'onboarding.step_launch_desc': 'Verificación final antes del lanzamiento',
    'onboarding.tip_identity': 'Asegúrese de que el nombre de la empresa coincida exactamente con el de sus estatutos. El RCCM y el ID Fiscal son esenciales para sus futuras facturas conformes.',
    'onboarding.tip_tax': 'El Sistema Normal es obligatorio para empresas que superen una cierta facturación. El SMT es adecuado para pequeñas estructuras.',
    'onboarding.tip_capital': 'Defina aquí el capital social inicial. Para una SARL en el área OHADA, el capital mínimo es generalmente de 1.000.000 FCFA.',
    'onboarding.tip_treasury': 'Configure sus cuentas de efectivo iniciales. El saldo inicial corresponde generalmente al capital desembolsado depositado.',
    'onboarding.tip_team': 'Defina los primeros usuarios. Por defecto, usted es el Administrador Principal con todos los derechos.',
    'onboarding.tip_modules': 'Solo active los módulos que necesite por ahora. Siempre puede activar otros más tarde.',
    'onboarding.tip_launch': 'Al hacer clic en "Lanzar aplicación", el sistema generará automáticamente los asientos de constitución.',
    'onboarding.initializing': 'Inicializando su entorno...',
    'onboarding.loading_step_1': 'Verificando datos...',
    'onboarding.loading_step_2': 'Creando el expediente de la empresa...',
    'onboarding.loading_step_3': 'Configurando el ejercicio fiscal...',
    'onboarding.loading_step_4': 'Inicializando el plan de cuentas...',
    'onboarding.loading_step_5': 'Generando asientos de constitución...',
    'onboarding.loading_step_6': 'Configurando la tesorería...',
    'onboarding.loading_step_7': 'Finalizando la incorporación...',
    'onboarding.error_generic': 'Ocurrió un error. Por favor, inténtelo de nuevo.',
    'onboarding.sidebar_title': 'Ayuda a la création',
    'onboarding.sidebar_tip_1': 'Asegúrese de que el nombre coincida con sus documentos oficiales.',
    'onboarding.sidebar_tip_2': 'El capital social mínimo depende de su forma jurídica.',
    'onboarding.sidebar_tip_3': 'Podrá añadir más usuarios más tarde.',
    'onboarding.feature_compliance': 'Cumplimiento',
    'onboarding.feature_compliance_desc': 'Cumplimiento estricto de las normas OHADA et fiscales locales.',
    'onboarding.feature_precision': 'Precisión',
    'onboarding.feature_precision_desc': 'Cálculos automatizados y tableros en tiempo real.',
    'onboarding.feature_modular': 'Modular',
    'onboarding.feature_modular_desc': 'Solo active las herramientas que necesite.',
    'onboarding.summary_identity': 'Identidad',
    'onboarding.summary_capital': 'Capital Social',
    'onboarding.summary_tax': 'Fiscalidad',
    'onboarding.summary_accounting': 'Contabilidad',
    'onboarding.summary_treasury': 'Cuentas de Tesorería',
    'onboarding.summary_modules': 'Módulos Activados',
    'onboarding.summary_ready': '¿Listo para empezar?',
    'onboarding.module_accounting': 'Contabilidad',
    'onboarding.module_invoicing': 'Facturación',
    'onboarding.module_crm': 'Clientes',
    'onboarding.module_vendors': 'Proveedores',
    'onboarding.module_payroll': 'Nómina',
    'onboarding.module_vat': 'IVA',
    'onboarding.module_assets': 'Activos',
    'onboarding.module_bankrec': 'Conciliación',
    'onboarding.module_accounting_desc': 'Diario, Mayor, Balance',
    'onboarding.module_invoicing_desc': 'Presupuestos, Facturas, Clientes',
    'onboarding.module_crm_desc': 'Fichas de clientes, Seguimiento',
    'onboarding.module_vendors_desc': 'Compras, Deudas, Pagos',
    'onboarding.module_payroll_desc': 'Nóminas, Social',
    'onboarding.module_vat_desc': 'Cálculo auto, Formularios',
    'onboarding.module_assets_desc': 'Amortizaciones, Registro',
    'onboarding.module_bankrec_desc': 'Punteo, Diferencias',
    'onboarding.summary_partners': 'Socios',
    'onboarding.summary_costs': 'gastos',
    'onboarding.summary_vat_exempt': 'Exento de IVA',
    'onboarding.summary_fiscal_start': 'Inicio',
    'onboarding.summary_auto_config': 'Configuración Automática Recomendada',
    'common.confirm_delete': '¿Está seguro de que desea eliminar este elemento?',
    'common.confirm_delete_title': 'Confirmar eliminación',
    'common.delete': 'Eliminar',
    'common.cancel': 'Cancelar',
    'common.confirm_irreversible': 'Esta acción es irreversible.',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.duplicate': 'Duplicar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.all': 'Todo',
    'common.none': 'Ninguno',
    'common.date': 'Fecha',
    'common.description': 'Descripción',
    'common.amount': 'Monto',
    'common.reference': 'Referencia',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.add': 'Añadir',
    'common.close': 'Cerrar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.finish': 'Finalizar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'journal.title': 'Diario de Operaciones',
    'journal.new_entry': 'Nueva Entrada',
    'journal.expert_mode': 'Modo Experto',
    'journal.guided_mode': 'Modo Guiado',
    'journal.balance': 'Equilibrar',
    'journal.balanced': 'Equilibrado',
    'journal.unbalanced': 'Desequilibrado',
    'journal.debit': 'Débito',
    'journal.credit': 'Crédito',
    'journal.account': 'Cuenta',
    'journal.vat': 'IVA',
    'journal.payment_mode': 'Modo de Pago',
    'journal.third_party': 'Tercero',
    'journal.notes': 'Notas',
    'journal.attachments': 'Adjuntos',
    'journal.ai_suggestions': 'Sugerencias IA',
    'journal.scan_invoice': 'Escanear Factura',
    'journal.export_pdf': 'Exportar a PDF',
    'journal.export_excel': 'Exportar a Excel',
    'journal.filter_date_range': 'Periodo',
    'journal.filter_status': 'Estado',
    'journal.search_placeholder': 'Buscar transacción...',
    'currency.title': 'Gestión de Divisas',
    'currency.description': 'Configure sus tipos de cambio por defecto.',
    'currency.add_rate': 'Añadir Tipo',
    'currency.from': 'De',
    'currency.to': 'A',
    'currency.rate': 'Tipo',
    'currency.updated_at': 'Última actualización',
    'currency.base_currency': 'Moneda base',
    'currency.convert': 'Convertir',
    'currency.analyzer_title': 'Analizador de Divisas',
    'currency.analyzer_description': 'Analice el impacto de las variaciones de cambio.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
